#!/bin/bash
# Code generated by protoc-gen-liquibase. DO NOT EDIT.

# Command Arguments
CHANGEEXECLISTENER=${1}
CHANGEEXECLISTENERCLASS=${2}
CHANGEEXECLISTENERPROPERTIESFILE=${3}
CHANGELOGFILE=${4}
CHANGELOGPARAMETERS=${5}
CONTEXTS=${6}
DATABASE=${7}
DATE=${8}
DEFAULTCATALOGNAME=${9}
DEFAULTSCHEMANAME=${10}
DRIVER=${11}
DRIVERPROPERTIESFILE=${12}
LABELFILTER=${13}
OUTPUTDEFAULTCATALOG=${14}
OUTPUTDEFAULTSCHEMA=${15}
PASSWORD=${16}
ROLLBACKSCRIPT=${17}
SKIPDATABASESTEP=${18}
URL=${19}
USERNAME=${20}
# Global Options
ALWAYSDROPINSTEADOFREPLACE=${21}
ALWAYSOVERRIDESTOREDLOGICSCHEMA=${22}
AUTOREORG=${23}
CHANGELOGLOCKPOLLRATE=${24}
CHANGELOGLOCKWAITTIMEINMINUTES=${25}
CHANGELOGPARSEMODE=${26}
CLASSPATH=${27}
CONVERTDATATYPES=${28}
DATABASECHANGELOGLOCKTABLENAME=${29}
DATABASECHANGELOGTABLENAME=${30}
DATABASECLASS=${31}
DDLLOCKTIMEOUT=${32}
DEFAULTSFILE=${33}
DIFFCOLUMNORDER=${34}
DUPLICATEFILEMODE=${35}
ERRORONCIRCULARINCLUDEALL=${36}
FILEENCODING=${37}
FILTERLOGMESSAGES=${38}
GENERATECHANGESETCREATEDVALUES=${39}
GENERATEDCHANGESETIDSCONTAINSDESCRIPTION=${40}
HEADLESS=${41}
HUBAPIKEY=${42}
HUBLOGLEVEL=${43}
HUBMODE=${44}
HUBURL=${45}
INCLUDECATALOGINSPECIFICATION=${46}
INCLUDESYSTEMCLASSPATH=${47}
LICENSEKEY=${48}
LIQUIBASECATALOGNAME=${49}
LIQUIBASESCHEMANAME=${50}
LIQUIBASETABLESPACENAME=${51}
LOGCHANNELS=${52}
LOGFILE=${53}
LOGFORMAT=${54}
LOGLEVEL=${55}
MIRRORCONSOLEMESSAGESTOLOG=${56}
MISSINGPROPERTYMODE=${57}
MONITORPERFORMANCE=${58}
NATIVEEXECUTOR=${59}
ONMISSINGINCLUDECHANGELOG=${60}
OUTPUTFILE=${61}
OUTPUTFILEENCODING=${62}
OUTPUTLINESEPARATOR=${63}
PRESERVESCHEMACASE=${64}
PROLICENSEKEY=${65}
PROMARKUNUSEDNOTDROP=${66}
PROSQLINLINE=${67}
PROSYNONYMSDROPPUBLIC=${68}
PROMPTFORNONLOCALDATABASE=${69}
PROPERTYPROVIDERCLASS=${70}
SEARCHPATH=${71}
SECUREPARSING=${72}
SHOULDRUN=${73}
SHOULDSNAPSHOTDATA=${74}
SHOWBANNER=${75}
SQLLOGLEVEL=${76}
STRICT=${77}
SUPPORTPROPERTYESCAPING=${78}
USEPROCEDURESCHEMA=${79}
VALIDATEXMLCHANGELOGFILES=${80}

if [[ -z "$CHANGELOGFILE" ]]; then
	echo "changelogFile is required"
	exit 1
fi
if [[ -z "$DATE" ]]; then
	echo "date is required"
	exit 1
fi
if [[ -z "$URL" ]]; then
	echo "url is required"
	exit 1
fi

PARAMS=()

if [[ -n "$CHANGEEXECLISTENER" ]]; then
	PARAMS+=("--change-exec-listener=$CHANGEEXECLISTENER")
fi
if [[ -n "$CHANGEEXECLISTENERCLASS" ]]; then
	PARAMS+=("--change-exec-listener-class=$CHANGEEXECLISTENERCLASS")
fi
if [[ -n "$CHANGEEXECLISTENERPROPERTIESFILE" ]]; then
	PARAMS+=("--change-exec-listener-properties-file=$CHANGEEXECLISTENERPROPERTIESFILE")
fi
if [[ -n "$CHANGELOGFILE" ]]; then
	PARAMS+=("--changelog-file=$CHANGELOGFILE")
fi
if [[ -n "$CHANGELOGPARAMETERS" ]]; then
	PARAMS+=("--changelog-parameters=$CHANGELOGPARAMETERS")
fi
if [[ -n "$CONTEXTS" ]]; then
	PARAMS+=("--contexts=$CONTEXTS")
fi
if [[ -n "$DATABASE" ]]; then
	PARAMS+=("--database=$DATABASE")
fi
if [[ -n "$DATE" ]]; then
	PARAMS+=("--date=$DATE")
fi
if [[ -n "$DEFAULTCATALOGNAME" ]]; then
	PARAMS+=("--default-catalog-name=$DEFAULTCATALOGNAME")
fi
if [[ -n "$DEFAULTSCHEMANAME" ]]; then
	PARAMS+=("--default-schema-name=$DEFAULTSCHEMANAME")
fi
if [[ -n "$DRIVER" ]]; then
	PARAMS+=("--driver=$DRIVER")
fi
if [[ -n "$DRIVERPROPERTIESFILE" ]]; then
	PARAMS+=("--driver-properties-file=$DRIVERPROPERTIESFILE")
fi
if [[ -n "$LABELFILTER" ]]; then
	PARAMS+=("--label-filter=$LABELFILTER")
fi
if [[ -n "$OUTPUTDEFAULTCATALOG" ]]; then
	PARAMS+=("--output-default-catalog=$OUTPUTDEFAULTCATALOG")
fi
if [[ -n "$OUTPUTDEFAULTSCHEMA" ]]; then
	PARAMS+=("--output-default-schema=$OUTPUTDEFAULTSCHEMA")
fi
if [[ -n "$PASSWORD" ]]; then
	PARAMS+=("--password=$PASSWORD")
fi
if [[ -n "$ROLLBACKSCRIPT" ]]; then
	PARAMS+=("--rollback-script=$ROLLBACKSCRIPT")
fi
if [[ -n "$SKIPDATABASESTEP" ]]; then
	PARAMS+=("--skip-database-step=$SKIPDATABASESTEP")
fi
if [[ -n "$URL" ]]; then
	PARAMS+=("--url=$URL")
fi
if [[ -n "$USERNAME" ]]; then
	PARAMS+=("--username=$USERNAME")
fi

GLOBALS=()

if [[ -n "$ALWAYSDROPINSTEADOFREPLACE" ]]; then
	GLOBALS+=("--always-drop-instead-of-replace=$ALWAYSDROPINSTEADOFREPLACE")
fi
if [[ -n "$ALWAYSOVERRIDESTOREDLOGICSCHEMA" ]]; then
	GLOBALS+=("--always-override-stored-logic-schema=$ALWAYSOVERRIDESTOREDLOGICSCHEMA")
fi
if [[ -n "$AUTOREORG" ]]; then
	GLOBALS+=("--auto-reorg=$AUTOREORG")
fi
if [[ -n "$CHANGELOGLOCKPOLLRATE" ]]; then
	GLOBALS+=("--changelog-lock-poll-rate=$CHANGELOGLOCKPOLLRATE")
fi
if [[ -n "$CHANGELOGLOCKWAITTIMEINMINUTES" ]]; then
	GLOBALS+=("--changelog-lock-wait-time-in-minutes=$CHANGELOGLOCKWAITTIMEINMINUTES")
fi
if [[ -n "$CHANGELOGPARSEMODE" ]]; then
	GLOBALS+=("--changelog-parse-mode=$CHANGELOGPARSEMODE")
fi
if [[ -n "$CLASSPATH" ]]; then
	GLOBALS+=("--classpath=$CLASSPATH")
fi
if [[ -n "$CONVERTDATATYPES" ]]; then
	GLOBALS+=("--convert-data-types=$CONVERTDATATYPES")
fi
if [[ -n "$DATABASECHANGELOGLOCKTABLENAME" ]]; then
	GLOBALS+=("--database-changelog-lock-table-name=$DATABASECHANGELOGLOCKTABLENAME")
fi
if [[ -n "$DATABASECHANGELOGTABLENAME" ]]; then
	GLOBALS+=("--database-changelog-table-name=$DATABASECHANGELOGTABLENAME")
fi
if [[ -n "$DATABASECLASS" ]]; then
	GLOBALS+=("--database-class=$DATABASECLASS")
fi
if [[ -n "$DDLLOCKTIMEOUT" ]]; then
	GLOBALS+=("--ddl-lock-timeout=$DDLLOCKTIMEOUT")
fi
if [[ -n "$DEFAULTSFILE" ]]; then
	GLOBALS+=("--defaults-file=$DEFAULTSFILE")
fi
if [[ -n "$DIFFCOLUMNORDER" ]]; then
	GLOBALS+=("--diff-column-order=$DIFFCOLUMNORDER")
fi
if [[ -n "$DUPLICATEFILEMODE" ]]; then
	GLOBALS+=("--duplicate-file-mode=$DUPLICATEFILEMODE")
fi
if [[ -n "$ERRORONCIRCULARINCLUDEALL" ]]; then
	GLOBALS+=("--error-on-circular-include-all=$ERRORONCIRCULARINCLUDEALL")
fi
if [[ -n "$FILEENCODING" ]]; then
	GLOBALS+=("--file-encoding=$FILEENCODING")
fi
if [[ -n "$FILTERLOGMESSAGES" ]]; then
	GLOBALS+=("--filter-log-messages=$FILTERLOGMESSAGES")
fi
if [[ -n "$GENERATECHANGESETCREATEDVALUES" ]]; then
	GLOBALS+=("--generate-changeset-created-values=$GENERATECHANGESETCREATEDVALUES")
fi
if [[ -n "$GENERATEDCHANGESETIDSCONTAINSDESCRIPTION" ]]; then
	GLOBALS+=("--generated-changeset-ids-contains-description=$GENERATEDCHANGESETIDSCONTAINSDESCRIPTION")
fi
if [[ -n "$HEADLESS" ]]; then
	GLOBALS+=("--headless=$HEADLESS")
fi
if [[ -n "$HUBAPIKEY" ]]; then
	GLOBALS+=("--hub-api-key=$HUBAPIKEY")
fi
if [[ -n "$HUBLOGLEVEL" ]]; then
	GLOBALS+=("--hub-log-level=$HUBLOGLEVEL")
fi
if [[ -n "$HUBMODE" ]]; then
	GLOBALS+=("--hub-mode=$HUBMODE")
fi
if [[ -n "$HUBURL" ]]; then
	GLOBALS+=("--hub-url=$HUBURL")
fi
if [[ -n "$INCLUDECATALOGINSPECIFICATION" ]]; then
	GLOBALS+=("--include-catalog-in-specification=$INCLUDECATALOGINSPECIFICATION")
fi
if [[ -n "$INCLUDESYSTEMCLASSPATH" ]]; then
	GLOBALS+=("--include-system-classpath=$INCLUDESYSTEMCLASSPATH")
fi
if [[ -n "$LICENSEKEY" ]]; then
	GLOBALS+=("--license-key=$LICENSEKEY")
fi
if [[ -n "$LIQUIBASECATALOGNAME" ]]; then
	GLOBALS+=("--liquibase-catalog-name=$LIQUIBASECATALOGNAME")
fi
if [[ -n "$LIQUIBASESCHEMANAME" ]]; then
	GLOBALS+=("--liquibase-schema-name=$LIQUIBASESCHEMANAME")
fi
if [[ -n "$LIQUIBASETABLESPACENAME" ]]; then
	GLOBALS+=("--liquibase-tablespace-name=$LIQUIBASETABLESPACENAME")
fi
if [[ -n "$LOGCHANNELS" ]]; then
	GLOBALS+=("--log-channels=$LOGCHANNELS")
fi
if [[ -n "$LOGFILE" ]]; then
	GLOBALS+=("--log-file=$LOGFILE")
fi
if [[ -n "$LOGFORMAT" ]]; then
	GLOBALS+=("--log-format=$LOGFORMAT")
fi
if [[ -n "$LOGLEVEL" ]]; then
	GLOBALS+=("--log-level=$LOGLEVEL")
fi
if [[ -n "$MIRRORCONSOLEMESSAGESTOLOG" ]]; then
	GLOBALS+=("--mirror-console-messages-to-log=$MIRRORCONSOLEMESSAGESTOLOG")
fi
if [[ -n "$MISSINGPROPERTYMODE" ]]; then
	GLOBALS+=("--missing-property-mode=$MISSINGPROPERTYMODE")
fi
if [[ -n "$MONITORPERFORMANCE" ]]; then
	GLOBALS+=("--monitor-performance=$MONITORPERFORMANCE")
fi
if [[ -n "$NATIVEEXECUTOR" ]]; then
	GLOBALS+=("--native-executor=$NATIVEEXECUTOR")
fi
if [[ -n "$ONMISSINGINCLUDECHANGELOG" ]]; then
	GLOBALS+=("--on-missing-include-changelog=$ONMISSINGINCLUDECHANGELOG")
fi
if [[ -n "$OUTPUTFILE" ]]; then
	GLOBALS+=("--output-file=$OUTPUTFILE")
fi
if [[ -n "$OUTPUTFILEENCODING" ]]; then
	GLOBALS+=("--output-file-encoding=$OUTPUTFILEENCODING")
fi
if [[ -n "$OUTPUTLINESEPARATOR" ]]; then
	GLOBALS+=("--output-line-separator=$OUTPUTLINESEPARATOR")
fi
if [[ -n "$PRESERVESCHEMACASE" ]]; then
	GLOBALS+=("--preserve-schema-case=$PRESERVESCHEMACASE")
fi
if [[ -n "$PROLICENSEKEY" ]]; then
	GLOBALS+=("--pro-license-key=$PROLICENSEKEY")
fi
if [[ -n "$PROMARKUNUSEDNOTDROP" ]]; then
	GLOBALS+=("--pro-mark-unused-not-drop=$PROMARKUNUSEDNOTDROP")
fi
if [[ -n "$PROSQLINLINE" ]]; then
	GLOBALS+=("--pro-sql-inline=$PROSQLINLINE")
fi
if [[ -n "$PROSYNONYMSDROPPUBLIC" ]]; then
	GLOBALS+=("--pro-synonyms-drop-public=$PROSYNONYMSDROPPUBLIC")
fi
if [[ -n "$PROMPTFORNONLOCALDATABASE" ]]; then
	GLOBALS+=("--prompt-for-non-local-database=$PROMPTFORNONLOCALDATABASE")
fi
if [[ -n "$PROPERTYPROVIDERCLASS" ]]; then
	GLOBALS+=("--property-provider-class=$PROPERTYPROVIDERCLASS")
fi
if [[ -n "$SEARCHPATH" ]]; then
	GLOBALS+=("--search-path=$SEARCHPATH")
fi
if [[ -n "$SECUREPARSING" ]]; then
	GLOBALS+=("--secure-parsing=$SECUREPARSING")
fi
if [[ -n "$SHOULDRUN" ]]; then
	GLOBALS+=("--should-run=$SHOULDRUN")
fi
if [[ -n "$SHOULDSNAPSHOTDATA" ]]; then
	GLOBALS+=("--should-snapshot-data=$SHOULDSNAPSHOTDATA")
fi
if [[ -n "$SHOWBANNER" ]]; then
	GLOBALS+=("--show-banner=$SHOWBANNER")
fi
if [[ -n "$SQLLOGLEVEL" ]]; then
	GLOBALS+=("--sql-log-level=$SQLLOGLEVEL")
fi
if [[ -n "$STRICT" ]]; then
	GLOBALS+=("--strict=$STRICT")
fi
if [[ -n "$SUPPORTPROPERTYESCAPING" ]]; then
	GLOBALS+=("--support-property-escaping=$SUPPORTPROPERTYESCAPING")
fi
if [[ -n "$USEPROCEDURESCHEMA" ]]; then
	GLOBALS+=("--use-procedure-schema=$USEPROCEDURESCHEMA")
fi
if [[ -n "$VALIDATEXMLCHANGELOGFILES" ]]; then
	GLOBALS+=("--validate-xml-changelog-files=$VALIDATEXMLCHANGELOGFILES")
fi

docker-entrypoint.sh "${GLOBALS[@]}" rollback-to-date-sql "${PARAMS[@]}"
